# Generated by Django 5.2.4 on 2025-07-10 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_loginrecord'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoginRecord',
        ),
    ]
