# Generated by Django 5.2.3 on 2025-07-13 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_expense_income'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_name',
        ),
    ]
